### ISSUE TITLE
Criar um banco de dados MongoDB carregado com dados fake dos logs da plataforma

### ISSUE THREAD

**Issue by AndreLars** [api-fatec-bd/api#13]
DoR: Task está pronta para começar
DoD: Pull Request completado para branch release e homologado pelo PO

- [x] Criar um banco de dados MongoDB carregado com dados fake dos logs da plataforma

**Comment by felipemessi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/NemoSys-614a426c6e937d0010e37579/issues/api-fatec-bd/api/13?planning-poker) with ZenHub @AndreLars @ferpsalles @JessicaIsri @PauloFilipini @Vitordan5

**Comment by angelog** [comment]
Na inserção tivemos que adicionar na string de conexção -> Localhost:27017/?retryWrites=false, para habilitar dados repitidos.

**Comment by angelog** [comment]
Foi feito a criação do Banco Logs e collection Login com 2.000 dados fakes de login e logout .

**Comment by AndreLars** [comment]
Falta algumas coisas para fechar a issue corretamente.
DoD: Pull Request completado para branch release e homologado pelo PO
