### ISSUE TITLE
Criar um job batch que roda 1 vez ao dia, extrai os dados FAKE do banco da plataforma, transforma para o DW e carrega no DW

### ISSUE THREAD

**Issue by AndreLars** [api-fatec-bd/api#14]
DoR: #13 Completado
DoD: Pull Request completado para branch release e homologado pelo PO

- [ ] Criar um job batch que roda 1 vez ao dia, extrai os dados FAKE do banco da plataforma, transforma para o DW e carrega no DW (horário com menos impacto na plataforma)

Recomendação: usar Apache Spark (Tem a biblioteca do Python, mas as vezes só ele conectando direto no Mongo resolve)

**Comment by felipemessi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/NemoSys-614a426c6e937d0010e37579/issues/api-fatec-bd/api/14?planning-poker) with ZenHub @aerosdan @AndreLars @angelog @ferpsalles @JessicaIsri @PauloFilipini @Vitordan5

**Comment by aerosdan** [comment]
dimensões mapeadas no ETL  do banco fake da plataforma
