### ISSUE TITLE
Criar um job batch que roda 1 vez ao dia, extrai os dados do banco do chat, transforma para o DW e carrega no DW

### ISSUE THREAD

**Issue by AndreLars** [api-fatec-bd/api#15]
DoR: Task está pronta para começar
DoD: Pull Request completado para branch release e homologado pelo PO

- [x] Criar um job batch que roda 1 vez ao dia, extrai os dados do banco chat, transforma para o DW e carrega no DW (horário com menos impacto na plataforma)

Recomendação: usar Apache Spark (Tem a biblioteca do Python, mas as vezes só ele conectando direto no Mongo resolve)

**Comment by felipemessi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/NemoSys-614a426c6e937d0010e37579/issues/api-fatec-bd/api/15?planning-poker) with ZenHub @aerosdan @AndreLars @angelog @ferpsalles @JessicaIsri @N4htan @PauloFilipini @Vitordan5

**Comment by aerosdan** [comment]
fact de sessões concluído.
outras facts TODO (necessário definir melhor  de onde virão as  informações dessas entidades e alinhar constraints de  integração)
