### ISSUE TITLE
Criar uma pipeline que realiza o build do projeto toda vez que é completado um PR para a branch release

### ISSUE THREAD

**Issue by AndreLars** [api-fatec-bd/api#17]
DoR: Task está pronta para começar
DoD: Pull Request completado para branch release e homologado pelo PO

- [x] Criar uma pipeline que realiza o build do projeto toda vez que é completado um PR para a branch release

**Comment by JessicaIsri** [comment]
A pipeline esta utilizando o template do django disponibilizado no próprio git, o build está sendo feito para as versões 3.7, 3.8 e 3.9, sendo possível adicionar ou remover versões, é recomendado que seja desenvolvido os testes unitários para as implementações feitas no django
