### ISSUE TITLE
Reestruturar, adaptar e Modelar o banco de dados da aplicação legada

### ISSUE THREAD

**Issue by felipemessi** [api-fatec-bd/api#2]
Descrição: A partir da aplicação escolhida que foi desenvolvida pela turma do 3ºsem de banco de dados, armazenar os dados de log em um banco não relacional.

Tasks:

- [x]  Analisar e entender a estrutura atual da aplicação, decidindo sobre qual tecnologia utilizar e documentar a justificativa da escolha (Como o banco escala horizontalmente, qual é a estratégia de particionamento, estimar o crescimento do volume de dados);
- [x]  Configurar o banco de dados, o Dockerfile (se for o caso) ;
- [x]  Criar a estrutura do banco de dados, definir quais serão os logs de acordo com as métricas (definidas no documento de requisitos);

**Comment by angelog** [comment]
A linguagem escolhida para execução do projeto foi python pois, temos mais familiaridade e traz recursos que vão nos auxiliar, juntamente com o projeto escolhido como base.
