### ISSUE TITLE
Realizar a configuração do ETL para processar eventos de ETL

### ISSUE THREAD

**Issue by felipemessi** [api-fatec-bd/api#25]
DoR: Desenvolver uma rotina de ETL para:

- [x] Processar os dados de eventos do LMS;

Com as seguintes características:

- [x] Alimentado incrementalmente;
- [x] Agendado para executar a atualização diariamente;

**Comment by felipemessi** [comment]
Ativação: quantos alunos/colaboradores acessaram a plataforma;
 Engajamento: quais alunos/colaboradores estão fazendo o curso no qual está matriculado;
 Desempenho: qual o aproveitamento -nota atingida -no curso no qual está matriculado;
 Participação x taxas de conclusão x desempenho dos alunos/colaboradores;
 Avaliação de reação: qualificação do conteúdo apresentado, experiência do aluno/colaborador durante o curso;
 Registro do tempo de participação no curso: tempo online executando as atividades

**Comment by Giovanniguidace** [comment]
![image](https://user-images.githubusercontent.com/62898187/140442886-366ce152-e248-48a6-bc71-b4b5d818e474.png)

Unit Tests OK!

**Comment by Giovanniguidace** [comment]
Tabelas finalizadas e com dados inseridos :  DIM_DISCIPLINA; DIM_CURSO; DIM_AULA; FACT_CHAT; FACT_USUARIO_CHAT; FACT_ACESSO;

**Comment by Giovanniguidace** [comment]
A task "Agendado para executar a atualização diariamente;" Já foi alinhado com Infra para a execução de uma Cron através do Linux. Será removido o Django e unificaremos em apenas um arquivo de execução na Cron. Será atualizado a cada 24 horas.

**Comment by aerosdan** [comment]
seguintes jobs estão funcionais:

etl\jobs\dim_turma_ETL.py
etl\jobs\dim_usuario_ETL_logs.py
etl\jobs\dim_usuario_ETL_rocketchat.py
etl\jobs\fact_aluno_aula_ETL.py
etl\jobs\fact_matricula_ETL.py
etl\jobs\fact_nota_ETL.py
etl\jobs\fact_usuario_conteudo_ETL.py

dinâmica de flags precisarei  replicar em alguns ETL de formas mais específica, mas a mecânica 'genérica' já foi desenvolvida e está 100% aplica na fact aluno aula.

@JessicaIsri arquivo crons (api\etl\crons) contem os crontabs que conversamos ontem

**Comment by Giovanniguidace** [comment]
Em breve o vídeo!

**Comment by Giovanniguidace** [comment]
https://user-images.githubusercontent.com/62898187/140590912-a0a7dba0-95fc-45f3-ba40-148d34fb8c6f.mp4

Vídeo aqui!
