### ISSUE TITLE
Criar um chat para interação entre tutor e aluno, aluno e aluno ou tutor e tutor

### ISSUE THREAD

**Issue by felipemessi** [api-fatec-bd/api#3]
Descrição: Criar um chat para interação entre tutor e aluno, aluno e aluno ou tutor e tutor que possa se integrar ao sistema legado e gere os logs pertinentes. A solução deve ter como característica ser integrável à outros projetos/plataformas.

Tasks: 

- [x]  Definir quais tecnologias serão utilizadas e documentar a justificativa da escolha, atendendo os seguintes requisitos: 1000 usuários simultâneos, ser capaz de coletar os dados do chat e definir os custos para escalar a aplicação;
- [x]  Implementar a solução de chat.

**Comment by AndreLars** [comment]
Usaremos o Rocket.chat
--- TODO justificativa
