### ISSUE TITLE
Configurar a extração e tratamento dos dados no ETL

### ISSUE THREAD

**Issue by felipemessi** [api-fatec-bd/api#4]
Descrição: Configurar a extração e tratamento dos dados no ETL (apenas etapas ET)

Tasks:

- [x]  Definir quais são as ferramentas ETL que serão utilizadas e documentar a justificativa da escolha, atendendo os requisitos: Ser integrável à um banco de dados não relacional e relacional.
- [x]  Implementar a solução com dados mockados (rotina), transformando os logs para carregar no DW (Apenas prepara o carregamento de dados).

**Comment by aerosdan** [comment]
a escolha da  ferramenta de extração e tratamento dos dados para ETL foi o framework Django, devido aos seguintes pontos:
* fácil conexão/integração  com Mongo DB e SQL SERVER;
* centralização do projeto;
* conhecimento mais abrangente/útil em relação às ferramentas especificas de ETL;
* curva de aprendizagem mais rápida e didática do que ferramentas prontas;
* maior liberdade de criação/personalização;

**Comment by Giovanniguidace** [comment]
Issues finalizadas! Resta incluir o vídeo aqui!!! 😀

**Comment by Giovanniguidace** [comment]
Vídeo apresentação

https://user-images.githubusercontent.com/62898187/133912105-8c21bb3e-057a-4fba-8bc0-d626840f5d15.mp4
