### ISSUE TITLE
Configurar o DW

### ISSUE THREAD

**Issue by felipemessi** [api-fatec-bd/api#5]
Descrição: Configurar o DW

Tasks:

- [x]  Definir quais são as ferramentas para o DW que serão utilizadas e documentar a justificativa da escolha, atendendo os requisitos: Banco de dados relacional e precisa atender os indicadores descritos no documento de requisitos.
- [x]  Definição das tabelas FATO, medidas, dimensões e granularidade (consultar professora Juliana)
- [x]  Implementar o DW

**Comment by ferpsalles** [comment]
Definição: SQL Server
Principais pontos:
- Como será a ferramenta utilizada na disciplina "Projeto de Data warehouse" teremos mais contato e meios de suporte com o sistema gerenciador.
- Recursos: Entre BigQuery e SQL Server, o SQL Server se torna mais viável por conta de não limitarmos ao free trial para realizar o projeto.
- Integração: Com o SQL Server é possível realizar a integração com Data Studio, tecnologia que está sendo cogitada para a construção dos dashboards e outras soluções sem muitos empecilhos.
- SQL Server Integration Services (SSIS) - componente da ferramenta que facilita a migração de dados para os processos de ETL.

**Comment by Vitordan5** [comment]
`-- -----------------------------------------------------
-- Table dim_usuario
-- -----------------------------------------------------
CREATE TABLE dim_usuario (
  id_usuario BIGINT IDENTITY NOT NULL PRIMARY KEY NONCLUSTERED,
  nome_usuario VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  tel_1 VARCHAR(45) NULL,
  tel_2 VARCHAR(45) NULL
 );

-- -----------------------------------------------------
-- Table dim_data
-- -----------------------------------------------------
CREATE TABLE dim_data (
  id_data BIGINT IDENTITY NOT NULL PRIMARY KEY NONCLUSTERED,
  dia INT NOT NULL,
  ano INT NOT NULL,
  semestre SMALLINT NOT NULL,
  trimestre SMALLINT NOT NULL,
  data DATETIME NOT NULL,
  hora INT NOT NULL,
  minuto INT NOT NULL,
  );


-- -----------------------------------------------------
-- Table dim_turma
-- -----------------------------------------------------
CREATE TABLE dim_turma (
  id_turma BIGINT IDENTITY NOT NULL PRIMARY KEY NONCLUSTERED,
  descricao VARCHAR(50) NOT NULL,
  id_professor BIGINT NOT NULL,
  INDEX fk_id_professor_idx (id_professor ASC),
  CONSTRAINT fk_id_professor
    FOREIGN KEY (id_professor)
    REFERENCES dim_usuario (id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
	GO



-- -----------------------------------------------------
-- Table dim_curso
-- -----------------------------------------------------
CREATE TABLE dim_curso (
  id_curso INT IDENTITY NOT NULL PRIMARY KEY NONCLUSTERED,
  descricao VARCHAR(50) NOT NULL,
  graduação VARCHAR(50) NOT NULL,
  duracao INT NOT NULL,
  )
GO


-- -----------------------------------------------------
-- Table dim_disciplina
-- -----------------------------------------------------
CREATE TABLE dim_disciplina (
  id_disciplina BIGINT IDENTITY NOT NULL PRIMARY KEY NONCLUSTERED,
  id_curso INT NOT NULL,
  descricao VARCHAR(50) NOT NULL,
  id_turma BIGINT NOT NULL,
  INDEX fk_id_curso_idx (id_curso ASC),
  CONSTRAINT fk_id_curso
    FOREIGN KEY (id_curso)
    REFERENCES dim_curso (id_curso)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
GO


-- -----------------------------------------------------
-- Table fact_matricula
-- -----------------------------------------------------
CREATE TABLE fact_matricula (
  id_matricula BIGINT PRIMARY KEY NOT NULL,
  data_inicio BIGINT NOT NULL REFERENCES dim_data (id_data),
  data_fim BIGINT NOT NULL REFERENCES dim_data (id_data),
  id_aluno BIGINT NOT NULL REFERENCES dim_usuario (id_usuario),
  id_turma BIGINT NOT NULL REFERENCES dim_turma (id_turma),
  id_disciplina BIGINT NOT NULL REFERENCES dim_disciplina (id_disciplina),
  id_certificado BIGINT NULL,
  numero_certificado VARCHAR(45) NULL,
  status_matricula BIT NOT NULL,
  quantidade_matriculas_ativa INT NOT NULL,
  quantidade_matriculas INT NOT NULL
  )
  GO

-- -----------------------------------------------------
-- Table fact_nota
-- -----------------------------------------------------
CREATE TABLE fact_nota (
  id_nota BIGINT PRIMARY KEY NOT NULL,
  id_aluno BIGINT NOT NULL REFERENCES dim_usuario (id_usuario),
  nota FLOAT NOT NULL,
  nota_avaliacao FLOAT NOT NULL,
  percentual_nota FLOAT NOT NULL,
  id_disciplina BIGINT NOT NULL REFERENCES dim_disciplina (id_disciplina),
  id_data BIGINT NOT NULL REFERENCES dim_data (id_data)
  )
  GO


-- -----------------------------------------------------
-- Table dim_aula
-- -----------------------------------------------------
CREATE TABLE dim_aula (
  id_aula BIGINT PRIMARY KEY NOT NULL,
  data BIGINT NOT NULL REFERENCES dim_data (id_data),
  id_disciplina BIGINT NOT NULL REFERENCES dim_disciplina (id_disciplina),
  titulo VARCHAR(45) NULL,
  duracao FLOAT NOT NULL,
  assunto VARCHAR(100) NULL,
  INDEX fk_id_disciplina_idx (id_disciplina ASC),
  INDEX fk_id_data_idx (data ASC) 
  )
GO


-- -----------------------------------------------------
-- Table fact_aluno_aula
-- -----------------------------------------------------
CREATE TABLE fact_aluno_aula (
  id_aluno_aula BIGINT PRIMARY KEY NOT NULL,
  id_aluno BIGINT NOT NULL REFERENCES dim_usuario (id_usuario),
  reacao_valor FLOAT NULL,
  data_reacao BIGINT NOT NULL REFERENCES dim_data (id_data),
  id_aula BIGINT NOT NULL REFERENCES dim_aula (id_aula),
  quantidade_msg INT NULL,
  tempo_participacao FLOAT NULL,
  media_reacao FLOAT NULL,

  INDEX fk_id_data_idx (data_reacao ASC),
  INDEX fk_id_aula_idx (id_aula ASC),
  INDEX fk_id_aluno_idx (id_aluno ASC)
  )
  GO


-- -----------------------------------------------------
-- Table fact_login_plataforma
-- -----------------------------------------------------
CREATE TABLE fact_login_plataforma (
  id_usuario BIGINT NOT NULL PRIMARY KEY REFERENCES dim_usuario (id_usuario),
  data_acesso BIGINT NOT NULL REFERENCES dim_data (id_data),
  quantidade_acesso INT NOT NULL,
  INDEX fk_id_data_idx (data_acesso ASC)
	)
GO
`

**Comment by Vitordan5** [comment]
O principal intuito do nosso Data Warehouse é conseguir entender o desempenho, a participação, tempo do aluno na plataforma e status do aluno em relação a matricula.

Para entender o desempenho temos a tabela "FACT_NOTA", nela são armazenados os registros das notas com as dimensões de identificação do aluno no qual a nota pertence, disciplina que foi avaliada, data em que foi aplicada a nota. Além do valor da nota que o aluno conseguiu temos também qual era o valor máximo possível na avaliação e qual foi o percentual atingido pelo aluno em relação a esse valor máximo  

O engajamento do aluno/colaborador no curso no qual estão vinculados é avaliado na tabela "FACT_MATRICULA" onde temos as dimensões das datas de inicio e fim (inicio e conclusão programada da matricula), aluno matriculado, turma (onde temos o professor que está lecionando a disciplina da matricula), identificação do certificado de conclusão caso seja finalizada com sucesso pelo aluno, status da matricula (se está ativa ou "trancada").

A quantidade de ativações do usuário na plataforma é encontrado na tabela "FACT_LOGIN_PLATAFORMA", na qual conseguimos observar em relação as dimensões de usuário e data do acesso.

Com o objetivo de registrar uma avaliação do aluno em relação ao conteúdo apresentado em aula criamos a tabela "FACT_ALUNO_AULA" nela temos o valor da reação (valor que o aluno atribuí aos materiais da aula), quantidade de mensagens que o aluno enviou durante a aula e tempo de participação do aluno (tempo entre sua primeira e ultima ação no chat da aula).

Fazendo uma combinação da tabelas "FACT_NOTA", "FACT_ALUNO_AULA" e "FACT_MATRICULA" podemos chegar a uma relação da participação do aluno aula com seu desempenho e a taxa de conclusão das disciplinas que o aluno foi matriculado.
