### ISSUE TITLE
Configurar o OLAP

### ISSUE THREAD

**Issue by felipemessi** [api-fatec-bd/api#6]
Descrição: Configurar o OLAP

Tasks:

- [x]  Definir quais são as ferramentas para o OLAP que serão utilizadas e documentar a justificativa da escolha, atendendo os requisitos: Possibilitar o acesso à diferentes níveis hierárquicos de usuário (administrador, gestor e tutor) e precisa atender as análises sugeridas a partir dos indicadores descritos no documento de requisitos.
- [x]  Implementar a solução com os dados mockados em um dashboard com os indicadores.

**Comment by felipemessi** [comment]
A escolha do Power BI foi a escolhida por ser uma ferramenta muito poderosa e completa, por ter um plano gratuito que facilita os estudos e porque não exige investimento.

**Comment by PauloFilipini** [comment]
Foi criado alguns protótipos utilizando a ferramenta DataStudio, para a criação dos prototipos foi utilizado dados mockados.

![image](https://user-images.githubusercontent.com/45483678/133944681-61d8d788-c48c-49a6-8eed-8ad03ec6f983.png)
![image](https://user-images.githubusercontent.com/45483678/133944684-42b16949-7979-4198-b5cd-7acba2689571.png)
![image](https://user-images.githubusercontent.com/45483678/133944696-f7b08271-7bed-462e-b184-0eaca8420d7e.png)
![image](https://user-images.githubusercontent.com/45483678/133944704-a0f85b76-b9d5-4123-9b76-e417f5be107b.png)
